const express=require('express');
const multer=require('multer');
const OpenAI=require('openai');
const sharp=require('sharp');
const DxfParser=require('dxf-parser');
const app=express();
const upload=multer({storage:multer.memoryStorage(),limits:{fileSize:25*1024*1024}});
const client=new OpenAI({apiKey:process.env.OPENAI_API_KEY,timeout:150000,maxRetries:2});
app.use(express.static(__dirname));
app.use(express.json({limit:'3mb'}));
const UNIT={D10:.56,D13:.995,D16:1.56},LAP={D10:450,D13:550,D16:650},STOCK=6000;
const CATEGORIES=['外周布基礎','内部布基礎','土間配筋','人通口補強筋','スリーブ補強'];
function selectedModel(){const m=process.env.OPENAI_VISION_MODEL||'';return(!m||m.includes('mini'))?'gpt-4o':m}
function cleanJson(t){const s=String(t||'{}').trim();try{return JSON.parse(s)}catch{}const m=s.match(/\{[\s\S]*\}/);if(m){try{return JSON.parse(m[0])}catch{}}return{error:'JSON parse failed',raw:s.slice(0,1000)}}
function apiKeyInfo(){const k=process.env.OPENAI_API_KEY||'';return{exists:!!k,prefix:k?k.slice(0,7):null,length:k.length}}
function isValidFabRow(r){const d=String(r?.dia||'').toUpperCase();return['D10','D13','D16'].includes(d)&&Number(r?.cut)>0&&Number(r?.qty)>0&&String(r?.member||'').trim()&&String(r?.shape||'').trim()}
function ensureBreakdown(p,page){p.foundation_breakdown=Array.isArray(p.foundation_breakdown)?p.foundation_breakdown:[];CATEGORIES.forEach(c=>{if(!p.foundation_breakdown.some(x=>x.category===c)){p.foundation_breakdown.push({category:c,page,status:'要確認',confidence:0,read:'',missing:'補完入力で加工帳化してください',spec:'',quantity_basis:'',action:'補完入力',geometry_hint:{kind:c.includes('土間')?'slab_mesh':c.includes('人通口')?'opening_reinforcement':c.includes('スリーブ')?'sleeve_reinforcement':'footing_line'},fabrication_rows:[]})}})}
function sanitize(p,page){p.page_classification=Array.isArray(p.page_classification)?p.page_classification:[];p.fabrication_book_rows=Array.isArray(p.fabrication_book_rows)?p.fabrication_book_rows.filter(isValidFabRow):[];p.foundation_breakdown=Array.isArray(p.foundation_breakdown)?p.foundation_breakdown.filter(x=>!String(x.category||'').includes('アンカー')).map(x=>({...x,fabrication_rows:Array.isArray(x.fabrication_rows)?x.fabrication_rows.filter(isValidFabRow):[]})):[];ensureBreakdown(p,page);return p}
async function jpegDataUrl(buffer){const buf=await sharp(buffer).rotate().resize({width:1800,withoutEnlargement:true}).jpeg({quality:88}).toBuffer();return`data:image/jpeg;base64,${buf.toString('base64')}`}
async function callVision({page,dataUrl}){const prompt=`あなたは30年選手の鉄筋積算担当者。対象は鉄筋屋の拾いのみ。アンカーボルト、型枠、コンクリート、設備配管は除外。基礎伏図/断面詳細/仕様欄から、外周布基礎、内部布基礎、土間配筋、人通口補強筋、スリーブ補強を必ず分解してJSONで返す。D10/D13/D16、@250、@300SC、人通口600x350、VU150を読んで、根拠・不足・補完入力に必要な数字を書く。確定できない加工帳行は出さない。返却形式:{"page_classification":[{"page":${page},"type":"基礎伏図","confidence":0,"reason":""}],"foundation_breakdown":[{"category":"外周布基礎","page":${page},"status":"要確認","confidence":0,"read":"","spec":"","quantity_basis":"","missing":"","action":"補完入力","geometry_hint":{},"fabrication_rows":[]}],"fabrication_book_rows":[],"warnings":[]}`;
 const r=await client.chat.completions.create({model:selectedModel(),response_format:{type:'json_object'},temperature:0,max_tokens:3500,messages:[{role:'user',content:[{type:'text',text:prompt},{type:'image_url',image_url:{url:dataUrl,detail:'high'}}]}]});
 return cleanJson(r.choices?.[0]?.message?.content||'{}')}
app.post('/api/analyze-page',upload.single('image'),async(req,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(500).json({error:'OPENAI_API_KEY is not set',apiKey:apiKeyInfo()});if(!req.file)return res.status(400).json({error:'image is required'});const page=req.body.page||1;const parsed=sanitize(await callVision({page,dataUrl:await jpegDataUrl(req.file.buffer)}),page);parsed._debug={mode:'vision',model:selectedModel(),page,bytes:req.file.size,apiKey:apiKeyInfo()};res.json(parsed)}catch(e){console.error(e);res.status(500).json({error:e.message||String(e),apiKey:apiKeyInfo()})}});
function pt(e){if(e.vertices?.length)return e.vertices.map(v=>({x:v.x||0,y:v.y||0}));if(e.startPoint&&e.endPoint)return[{x:e.startPoint.x||0,y:e.startPoint.y||0},{x:e.endPoint.x||0,y:e.endPoint.y||0}];return[]}
function lenPts(ps){let s=0;for(let i=1;i<ps.length;i++)s+=Math.hypot(ps[i].x-ps[i-1].x,ps[i].y-ps[i-1].y);return s}
function bbox(ents){let xs=[],ys=[];ents.forEach(e=>pt(e).forEach(p=>{xs.push(p.x);ys.push(p.y)}));if(!xs.length)return null;return{minX:Math.min(...xs),maxX:Math.max(...xs),minY:Math.min(...ys),maxY:Math.max(...ys),w:Math.max(...xs)-Math.min(...xs),h:Math.max(...ys)-Math.min(...ys)}}
function textOf(e){return String(e.text||e.string||e.value||'').trim()}
function dxfAnalyze(txt){const parser=new DxfParser();const dxf=parser.parseSync(txt);const ents=dxf.entities||[];const texts=ents.map(textOf).filter(Boolean);const textAll=texts.join(' ');const layers=[...new Set(ents.map(e=>e.layer).filter(Boolean))];const lines=ents.filter(e=>['LINE','LWPOLYLINE','POLYLINE'].includes(e.type));const box=bbox(lines)||{w:0,h:0};const totalLine=lines.reduce((s,e)=>s+lenPts(pt(e)),0);const d10=/D10/i.test(textAll),d13=/D13/i.test(textAll),d16=/D16/i.test(textAll);const pitch=(textAll.match(/[@＠]\s*(\d{2,4})/)||[])[1]||'';const opening=(textAll.match(/600\s*[x×]\s*350|人通口/gi)||[]);const sleeve=(textAll.match(/VU\s*150|φ\s*150|スリーブ/gi)||[]);return{project_type:'鉄筋工事',page_classification:[{page:1,type:'CAD/DXF',confidence:.95,reason:'DXFの線・文字・レイヤーを直接解析'}],spec_master:{rebar:`${d10?'D10 ':''}${d13?'D13 ':''}${d16?'D16 ':''}`.trim(),lap:LAP,stock:STOCK,unit_weight:UNIT,layers},cad_metrics:{layers,entity_count:ents.length,line_count:lines.length,total_line_length:Math.round(totalLine),bbox:box,text_hits:texts.slice(0,80)},foundation_breakdown:[{category:'外周布基礎',page:1,status:'要確認',confidence:.6,read:`DXF線分総延長 ${Math.round(totalLine)} / D13検出:${d13}`,spec:d13?'D13主筋候補':'D13未検出',quantity_basis:'CAD線分から延長候補を取得。外周/内部のレイヤー分離が必要',missing:'外周基礎レイヤーまたは外周線の選別',action:'延長確認',geometry_hint:{kind:'footing_line',dia:d13?'D13':''},fabrication_rows:[]},{category:'内部布基礎',page:1,status:'要確認',confidence:.55,read:`D10@${pitch||'不明'} 検出:${d10}`,spec:d10?`D10${pitch?'@'+pitch:''}`:'D10未検出',quantity_basis:'CAD線分から内部基礎線候補を取得',missing:'内部布基礎レイヤーまたは内部線の選別',action:'延長確認',geometry_hint:{kind:'footing_line',dia:'D10',pitch:Number(pitch)||0},fabrication_rows:[]},{category:'土間配筋',page:1,status:'要確認',confidence:.5,read:`DXF外接範囲 ${Math.round(box.w)} x ${Math.round(box.h)} / ${d10?'D10検出':''}${pitch?' @'+pitch:''}`,spec:d10?`D10${pitch?'@'+pitch:''}`:'',quantity_basis:'CAD外接範囲から土間範囲候補を取得',missing:'土間範囲の確定',action:'面積確認',geometry_hint:{kind:'slab_mesh',dia:'D10',pitch:Number(pitch)||250},fabrication_rows:[]},{category:'人通口補強筋',page:1,status:opening.length?'要確認':'要確認',confidence:opening.length?.7:.2,read:opening.join(' / '),spec:opening.length?'600x350補強候補':'',quantity_basis:'DXF文字から人通口候補を抽出',missing:'箇所数と補強形状',action:'箇所確認',geometry_hint:{kind:'opening_reinforcement',width:600,height:350,count:0},fabrication_rows:[]},{category:'スリーブ補強',page:1,status:sleeve.length?'要確認':'要確認',confidence:sleeve.length?.7:.2,read:sleeve.join(' / '),spec:sleeve.length?'VU150/φ150補強候補':'',quantity_basis:'DXF文字からスリーブ候補を抽出',missing:'箇所数と補強形状',action:'箇所確認',geometry_hint:{kind:'sleeve_reinforcement',width:150,height:150,count:0},fabrication_rows:[]}],fabrication_book_rows:[],warnings:['CADはPDF画像より文字・線・レイヤーを直接読めます。ただし外周/内部のレイヤー名が未整理の場合は選別確認が必要です。']}}
app.post('/api/analyze-dxf',upload.single('file'),async(req,res)=>{try{if(!req.file)return res.status(400).json({error:'dxf file is required'});const txt=req.file.buffer.toString('utf8');const parsed=dxfAnalyze(txt);parsed._debug={mode:'dxf',bytes:req.file.size};res.json(parsed)}catch(e){console.error(e);res.status(500).json({error:e.message||String(e),hint:'DXF形式を確認してください。DWGは一度DXFに変換してください。'})}});
app.get('/health',(_,res)=>res.json({ok:true,mode:'vision-and-dxf-takeoff',model:selectedModel(),apiKey:apiKeyInfo()}));
app.get('/api/check-openai',async(_,res)=>{try{if(!process.env.OPENAI_API_KEY)return res.status(500).json({ok:false,error:'OPENAI_API_KEY is not set',apiKey:apiKeyInfo()});res.json({ok:true,model:selectedModel(),apiKey:apiKeyInfo()})}catch(e){res.status(500).json({ok:false,error:e.message||String(e),apiKey:apiKeyInfo()})}});
const port=process.env.PORT||3000;app.listen(port,()=>console.log(`RebarOS server running on ${port}`));
